.PHONY: install_deps
install_deps:
	pip3 install -r requirements.txt && pip install -r requirements-dev.txt

.PHONY: test-unit
test-unit:
	python3 -b -m pytest tests

lint:
	python3 -m flake8

.PHONY: mypy
mypy:
	mypy --ignore-missing-imports --follow-imports=skip --strict-optional --warn-no-return .

.PHONY: isort_check
isort_check:
	isort ./ --check --diff

.PHONY: test
test: test-unit lint mypy isort_check
