apiVersion: v1
description: Amundsen is a metadata driven application for improving the productivity of data analysts, data scientists and engineers when interacting with data.
name: amundsen
version: 2.0.0
icon: https://github.com/amundsen-io/amundsen/blob/master/docs/img/logos/amundsen_logo_on_light.svg
home: https://www.amundsen.io/amundsen/
maintainers:
  - name: Amundsen TSC
    email: amundsen-tsc@lists.lfai.foundation
sources:
  - https://www.amundsen.io/amundsen/
  - https://github.com/amundsen-io/amundsen/
keywords:
  - metadata
  - data-catalog
  - data-discovery
  - linuxfoundation
  - amundsen
dependencies:
  - name: elasticsearch
    version: 1.32.5
    repository: https://charts.helm.sh/stable/
    condition: elasticsearch.enabled
