{{- if and .Values.neo4j.enabled .Values.neo4j.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-neo4j
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    component: neo4j
    {{- include "amundsen.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.neo4j.persistence.accessMode }}
  storageClassName: "{{ default "" .Values.neo4j.persistence.storageClass }}"
  resources:
    requests:
      storage: {{ default "3Gi" .Values.neo4j.persistence.size }}
{{- end }}
