{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: oidc-config-{{ .Values.frontend.service.name }}
    namespace: {{ .Release.Namespace }}
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.frontend.oidc.client.secret }}
  client_secrets.json: |-
    {
      "web": {
        "client_id": "{{ .Values.frontend.oidc.client.id }}",
        "client_secret": "{{ .Values.frontend.oidc.client.secret }}",
        "auth_uri": "{{ .Values.oidc.provider.auth_uri }}",
        "token_uri": "{{ .Values.oidc.provider.token_uri }}",
        "issuer": "{{ .Values.oidc.provider.issuer }}",
        "userinfo_uri": "{{ .Values.oidc.provider.userinfo_uri }}",
        "redirect_uris": [
          "{{ .Values.frontend.baseURL }}/*"
        ],
        "token_introspection_uri": "{{ .Values.oidc.provider.token_introspection_uri }}"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-config-{{ .Values.metadata.service.name }}
    namespace: {{ .Release.Namespace }}
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.metadata.oidc.client.secret }}
  client_secrets.json: |-
    {
      "web": {
        "client_id": "{{ .Values.metadata.oidc.client.id }}",
        "client_secret": "{{ .Values.metadata.oidc.client.secret }}",
        "auth_uri": "{{ .Values.oidc.provider.auth_uri }}",
        "token_uri": "{{ .Values.oidc.provider.token_uri }}",
        "issuer": "{{ .Values.oidc.provider.issuer }}",
        "userinfo_uri": "{{ .Values.oidc.provider.userinfo_uri }}",
        "redirect_uris": [
          "{{ .Values.metadata.baseURL }}/*"
        ],
        "token_introspection_uri": "{{ .Values.oidc.provider.token_introspection_uri }}"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-config-{{ .Values.search.service.name }}
    namespace: {{ .Release.Namespace }}
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.search.oidc.client.secret }}
  client_secrets.json: |-
    {
      "web": {
        "client_id": "{{ .Values.search.oidc.client.id }}",
        "client_secret": "{{ .Values.search.oidc.client.secret }}",
        "auth_uri": "{{ .Values.oidc.provider.auth_uri }}",
        "token_uri": "{{ .Values.oidc.provider.token_uri }}",
        "issuer": "{{ .Values.oidc.provider.issuer }}",
        "userinfo_uri": "{{ .Values.oidc.provider.userinfo_uri }}",
        "redirect_uris": [
          "{{ .Values.search.baseURL }}/*"
        ],
        "token_introspection_uri": "{{ .Values.oidc.provider.token_introspection_uri }}"
      }
    }
{{- end }}
