{{ if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-neo4j
  labels:
    component: neo4j
    run: neo4j
    {{- include "amundsen.labels" . | nindent 4 }}
{{- with .Values.neo4j.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end}}
spec:
  type: {{ .Values.neo4j.serviceType }}
  selector:
    component: neo4j
    {{- include "amundsen.selectorLabels" . | nindent 4 }}
  ports:
    - port: 7473
      name: neo4j-{{ .Values.environment }}-https
      targetPort: 7473
    - port: 7474
      name: neo4j-{{ .Values.environment }}-http
      targetPort: 7474
    - port: 7687
      name: neo4j-{{ .Values.environment }}-bolt
      targetPort: 7687
    - port: 1337
      name: neo4j-{{ .Values.environment }}-shell
      targetPort: 1337
{{ end }}
