{{- if and .Values.neo4j.enabled .Values.neo4j.persistence .Values.neo4j.persistence.efs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-neo4j
  labels:
    component: neo4j
    {{- include "amundsen.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ default "3Gi" .Values.neo4j.persistence.size }}
  nfs:
    server: {{ .Values.neo4j.persistence.efs.dns }}
    path: "/"
{{- end }}